version: "3"
volumes:
  nextcloud-data:
  nextcloud-db:
  npm-data:
  npm-ssl:
  npm-db:


networks:
  frontend:
    # add this if the network is already existing!
    # external: true
  backend:

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=NotMyPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=http
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=NotMyPassword
      - MYSQL_PASSWORD=NotMyPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
  code:
    image: collabora/code:latest
    restart: always
    ports:
      - "9980:9980"
    cap_add:
      - MKNOD
    environment:
      - password=NotMyPassword
      - username=admin
      - domain=code
      - extra_params=--o:ssl.enable=false
    networks:
      - frontend
